### ISSUE TITLE
MCMC in GaussianProcesses.jl

### ISSUE THREAD

**Issue by chris-nemeth** [JuliaStats/Klara.jl#167] opened 2017-08-07 10:07 UTC
Hi Theo,

Thanks for fixing the deprecation errors. 

We have a world age issue with our default Klara implementation within [GaussianProcesses.jl](https://github.com/STOR-i/GaussianProcesses.jl). Our `mcmc` function can be found here [mcmc](https://github.com/STOR-i/GaussianProcesses.jl/blob/master/src/mcmc.jl). As you can see it's a pretty straightforward MALA sampler. 

If you run the following as a test you'll see the error
```

using GaussianProcesses
import Distributions:Normal

srand(112233)
X = rand(20);
X = sort(X);
y = sin.(10*X);
y=convert(Vector{Bool}, y.>0);

#Select mean, kernel and likelihood function
mZero = MeanZero()   #Zero mean function
kern = SE(0.0,0.0)   #Sqaured exponential kernel (note that hyperparameters are on the log scale)
lik = BernLik()      #Bernoulli likelihood

gp = GP(X,vec(y),mZero,kern,lik)     

set_priors!(gp.k,[Normal(0.0,2.0),Normal(0.0,2.0)])

samples = mcmc(gp)
```

Thanks,

Chris

**Comment by scidom** [comment] 2017-08-07 12:11
Thanks Chris, leave it with me and I will check it. These world age issues in Julia v0.6 have become my nightmare... if anything else fails, I might have to remove code generation from the package...

**Comment by chris-nemeth** [comment] 2017-08-07 15:10
You may have already seen this and not sure if their solution helps [world age](https://docs.julialang.org/en/stable/manual/methods/#Redefining-Methods-1)?

**Comment by scidom** [comment] 2017-08-07 20:04
I am trying to reproduce your error Chris, to start with, but I get the error

```
julia> lik = BernLik()      #Bernoulli likelihood
ERROR: UndefVarError: BernLik not defined
```

Where is `BernLik()` defined, do I need to import it from somewhere? You may pass on a fully operational script-example (or fully breaking considering the world age issue), and I will work with it.

**Comment by chris-nemeth** [comment] 2017-08-07 21:30
Sorry. I should have mentioned that the non-Gaussian likelihoods aren't on the Julia package repository. You'll need to clone the package from Github.

**Comment by scidom** [comment] 2017-08-08 19:13
I can see the error now Chris. I will ask the community if there is a way to solve the world age issue, or else the package needs re-development.

**Comment by scidom** [comment] 2017-08-08 20:16
Here is the discussion at discourse:

https://discourse.julialang.org/t/world-age-issue-due-to-code-generation-inside-an-inner-constructor-in-julia-v0-6/5124

**Comment by chris-nemeth** [comment] 2017-08-08 20:22
Hopefully there's a simple solution to this and it doesn't create too much extra work for you.

**Comment by scidom** [comment] 2017-08-08 21:03
Indeed, let's hope Chris, as now nearly everything is code-generated and (world-) aged...

**Comment by scidom** [comment] 2017-08-09 15:27
@ararslan, @@JeffBezanson, @Keno, I know I have been asked before to post on discourse rather than tagging people. Unfortunately discourse hasn't been so helpful, and as you can see [here](https://discourse.julialang.org/t/world-age-issue-due-to-code-generation-inside-an-inner-constructor-in-julia-v0-6/5124) my issue remains unresolved. Without of course wanting you to fix the current Julia issue opened by @chris-nemeth, can you possibly provide a working solution for the issue mentioned at discourse (although I am afraid there isn't one, because some loss of functionality was incurred from Julia v0.5 to v0.6 in relation to this matter)? Your help would be greatly appreciated, as my package is currently broken due to this problem.

**Comment by scidom** [comment] 2017-08-10 07:27
@chris-nemeth, as you will see below, the following works. I extracted the code from your `mcmc()` method and it now executes. So, weirdly enough, the problem appears only when the same code ins enclosed into a function (your `mcmc()`):

```
using Klara
using GaussianProcesses
import Distributions:Normal

srand(112233)
X = rand(20);
X = sort(X);
y = sin.(10*X);
y=convert(Vector{Bool}, y.>0);

#Select mean, kernel and likelihood function
mZero = MeanZero()   #Zero mean function
kern = SE(0.0,0.0)   #Sqaured exponential kernel (note that hyperparameters are on the log scale)
lik = BernLik()      #Bernoulli likelihood

gp = GP(X,vec(y),mZero,kern,lik)     

set_priors!(gp.k,[Normal(0.0,2.0),Normal(0.0,2.0)])

start = GaussianProcesses.get_params(gp)
sampler=Klara.MALA(0.1)
mcrange=Klara.BasicMCRange(nsteps=5000, burnin=1000)

function logtarget(hyp::Vector{Float64})  #log-target
  GaussianProcesses.set_params!(gp, hyp)
  return GaussianProcesses.update_target!(gp)   
end

function dlogtarget(hyp::Vector{Float64}) #gradient of the log-target
  GaussianProcesses.set_params!(gp, hyp)
  return GaussianProcesses.update_target_and_dtarget!(gp)
end

starting = Dict(:p=>start)
q = BasicContMuvParameter(:p, logtarget=logtarget, gradlogtarget=dlogtarget) 
model = likelihood_model(q, false)               #set-up the model
tune = AcceptanceRateMCTuner(0.6, verbose=true)  #set length of tuning (default to burnin length)
job = BasicMCJob(model, sampler, mcrange, starting)   #set-up MCMC job
run(job)
chain = Klara.output(job)
```

**Comment by scidom** [comment] 2017-08-10 07:28
P.S. Of course this doesn't solve the problem, just letting you know what happens.

**Comment by chris-nemeth** [comment] 2017-08-10 13:48
You are right that it works outside of the `mcmc()` function although I can't see why that is.

**Comment by scidom** [comment] 2017-08-11 12:01
I don't know either Chris, it has to do with the new world age counter introduce in Julia v0.6 that messes up Klara. I will try to sort this out by basically dropping code-generation from my package, but this will take me a while, it requires massive amount of work.

**Comment by chris-nemeth** [comment] 2017-08-11 12:41
If everything else in [Klara.jl](https://github.com/JuliaStats/Klara.jl/) works fine then it's not worth modifying the package just for [GaussianProcesses.jl](https://github.com/STOR-i/GaussianProcesses.jl).

**Comment by scidom** [comment] 2017-08-11 13:54
What would happen in this case though with GaussianProcesses? Can you see a workaround for your package? The main difficulty is that the methods in Klara can't be encapsulated in a function body anymore as it seems...

**Comment by chris-nemeth** [comment] 2017-08-11 14:04
For the time being, I can implement an HMC algorithm for the `mcmc()` function.

**Comment by scidom** [comment] 2017-08-11 14:11
Thanks Chris, sounds good, as it's going to take quite some time before I succeed in removing code generation from the whole codebase.

**Comment by scidom** [comment] 2017-08-11 20:03
Keno provided a solution on discourse, which solved this world age. Of course, there are many more world age errors to resolve before the GaussianProcesses can operate, but my hope is that the rest of the errors are now soluble in a similar way. I will check this out.

**Comment by scidom** [comment] 2017-08-12 22:23
I updated discourse with one new issue I encountered while trying to convert all the `eval()` calls to macro invocations. I replicate below the post from discourse to increase visibility as well as the likelihood of finding a solution.

The following works:

```
macro codegen(y)
  quote
    function (x::$(typeof(y)))
      x+1
    end
  end
end

f = @codegen(2.)
f(3.)
```

However, if I try to call the macro from inside a function (function g() below), the following fails:

```
g(y) = @codegen(y)

f = g(2.)
f(3.)
```

Is there a way to solve this issue by possibly modifying the macro somehow?

**Comment by scidom** [comment] 2017-08-27 07:15
Update; I removed several world-age errors associated with the main parameter methods and autodiff. There is still quite some work to do to eliminate all world age issues, so I will leave this ticket open till I am done. I am using your older breaking code @chris-nemeth to check when things will work completely from your end.

**Comment by scidom** [comment] 2017-09-08 16:59
After my last commit, your initial old GP example script runs for MALA without world age errors. I still need to make the analogous changes for all other samplers, streams and nstates before code-generation is eliminated completely, but perhaps about half of the job is done by now, seeing your initial code is operational.

**Comment by chris-nemeth** [comment] 2017-09-14 03:03
Thanks. That's great news! I'm away at the monent but I'll look at this when I return.

**Comment by scidom** [comment] 2017-10-08 13:37
After the latest upgrade to Klara v0.9.1, there is no code generation anymore in Klara in order to avoid world-age issues. This means that this issue has also been resolved, as there is no way you'd encounter any further world age errors. I will now close the issue.

**Closed by scidom** 2017-10-08 13:37 UTC

**Comment by chris-nemeth** [comment] 2017-10-13 11:26
Thanks for taking this.
